# Numpy ndarray

In [1]:
import numpy as np

In [2]:
list1 = [1, 2, 3]
print('list1 type: ', type(list1))

list1 type:  <class 'list'>


In [3]:
array1 = np.array(list1)
print('array1 type:', type(array1))
print('array1 type form:', array1.shape)

array1 type: <class 'numpy.ndarray'>
array1 type form: (3,)


In [7]:
array2 = np.array([[1,2,3],
                 [2,3,4]])
print('array2 type:', type(array2))
print('array2 type form:', array2.shape)

array2 type: <class 'numpy.ndarray'>
array2 type form: (2, 3)


In [8]:
array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 type form:', array3.shape)

array3 type: <class 'numpy.ndarray'>
array3 type form: (1, 3)


In [9]:
print('array1: {:0}, array2 {:1}, array3 {:2}'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1, array2 2, array3  2


# ndarray의 데이터 타입

In [10]:
list1 = [1,2,3]
print(type(list1))

<class 'list'>


In [12]:
array1=np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'numpy.ndarray'>
[1 2 3] int32


In [13]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

['1' '2' 'test'] <U11


In [14]:
list3 =[1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

[1. 2. 3.] float64


In [15]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [17]:
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [18]:
array_float1 = np.array([1.1, 2.2, 3.3])
array_int2 = array_float.astype('int32')
print(array_int2, array_int2.dtype)

[1 2 3] int32


# ndarray를 편리하게 생성하기-arange, zeros, ones

In [19]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [20]:
zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [22]:
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


# ndarray의 차원과 크기를 변경하는 reshape

In [23]:
array1 = np.arange(10)
print('array1:\n', array1)

array1:
 [0 1 2 3 4 5 6 7 8 9]


In [24]:
array2 = array1.reshape(2,5)
print('array2: \n', array2)

array2: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [25]:
array3 = array2.reshape(5,2)
print('array3: \n', array3)

array3: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [28]:
array3.reshape(10, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [29]:
array1 = np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
array2 = array1.reshape(-1, 5)
print('array2 \n', array2)

array2 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [33]:
array3 = array1.reshape(5, -1)
print('array3 \n', array3)

array3 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [36]:
array1 = np.arange(10)
array4 = array1.reshape(-1, 1)
print(array4)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [48]:
array1 = np.arange(8)
array3d = array1.reshape(2,2,2)
print('array3d \n', array3d)
print('\narray3d tolist: ', array3d.dtype)
print('array3d tolist: ', array3d.shape)
print('array3d tolist: ', array3d.tolist())

array3d 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

array3d tolist:  int32
array3d tolist:  (2, 2, 2)
array3d tolist:  [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [51]:
array5 = array3d.reshape(-1,1)
print('array5 \n', array5.tolist())
print('array5 \n', array5.shape)

array5 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 
 (8, 1)


In [54]:
array6 = array1.reshape(-1,1)
print('array6 \n', array6.tolist())
print('array6 \n', array6.shape)

array6 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 
 (8, 1)


# 넘파이 ndarray의 데이터 세트 선택하기 - indexing

- 단일 인덱싱

In [57]:
array1 = np.arange(start=1, stop=10)
print('array1: ', array1)

array1:  [1 2 3 4 5 6 7 8 9]


In [58]:
array1[2]

3

In [59]:
type(array1[2])

numpy.int32

In [61]:
print('맨 뒤의 값:', array1[-1], ', 맨 뒤에서 두번째 값: ', array1[-2])

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값:  8


In [62]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [65]:
print('row=0, col=0 : ', array2d[0,0])
print('row=0, col=1 : ', array2d[0,1])
print('row=1, col=0 : ', array2d[1,0])
print('row=1, col=1 : ', array2d[1,1])

row=0, col=0 :  1
row=0, col=1 :  2
row=1, col=0 :  4
row=1, col=1 :  5


- 슬라이싱 인덱싱

In [69]:
array1 = np.arange(1,10)
print('array1: ', array1)
array3 = array1[0:3]
print('array3: ', array3)
print(type(array3))
print(array3.dtype)

array1:  [1 2 3 4 5 6 7 8 9]
array3:  [1 2 3]
<class 'numpy.ndarray'>
int32


In [71]:
array1 = np.arange(start=1, stop=10)
array4 = array1[0:3]
print(array4)

[1 2 3]


In [74]:
array1d = np.arange(1, 21)
array2d = array1d.reshape(4,5)
print(array2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [78]:
print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:,:] \n', array2d[:,:])
print('array2d[0:2, 0:2] \n', array2d[:2, 1:])
print('array2d[0:2, 0:2] \n', array2d[:2, 0])

0:2, 0:2 
 [[1 2]
 [6 7]]
[[ 6  7  8]
 [11 12 13]]
[[ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 2  3  4  5]
 [ 7  8  9 10]]
[1 6]


In [94]:
print(array2d[0])
print(array2d[1])
print(array2d[:2, :3])

[1 2 3 4 5]
[ 6  7  8  9 10]
[[1 2 3]
 [6 7 8]]


In [95]:
print(array2d[0].shape)
print(array2d[1].shape)
print(array2d[3].shape)
print(array2d[:2, :3].shape)

(5,)
(5,)
(5,)
(2, 3)


- 팬시 인덱싱

In [100]:
array1d = np.arange(start=1, stop=10)
print(array1d)
array2 = array1d[array1d < 5]
print(array2)
arrya3 = array1d[array1d > 5]
print(arrya3)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4]
[6 7 8 9]


In [101]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [102]:
val = array1d > 5
print(val, type(val), val.shape)

[False False False False False  True  True  True  True] <class 'numpy.ndarray'> (9,)


In [103]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print(array3)

[6 7 8 9]


In [105]:
array1d = np.arange(1, 10)
target = []
for i in range(0, 9):
    if array1d[i] > 5:
        target.append(array1d[i])

array_selected = np.array(target)
print(array_selected)

[6 7 8 9]


In [107]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print(array4)

[6 7 8 9]


# 행렬의 정렬-sort()와 argsort()

- 행렬 정렬

In [108]:
org_array = np.array([3, 1, 9, 5])
print(org_array)

[3 1 9 5]


In [109]:
sort_array1 = np.sort(org_array)
print(sort_array1)
print(org_array)

[1 3 5 9]
[3 1 9 5]


In [111]:
sort_array2 = org_array.sort()
print(sort_array2)
print(org_array)

None
[1 3 5 9]


In [113]:
org_array

array([1, 3, 5, 9])

In [115]:
sort_array1_desc = np.sort(org_array)[::-1]
print(sort_array1_desc)

[9 5 3 1]


In [118]:
array2d = np.array([[8, 12],
                  [7, 1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print(sort_array2d_axis0)
sort_array2d_axis1 = np.sort(array2d, axis=1)
print(sort_array2d_axis1)

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


- 정렬 행렬의 인덱스 변환

In [120]:
org_array = np.array([3,1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print(sort_indices)

<class 'numpy.ndarray'>
[1 0 3 2]


In [121]:
org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print(sort_indices_desc)

[2 3 0 1]


In [124]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([76, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print(sort_indices_asc)
print(name_array[sort_indices_asc])

[0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


# 선형대수 연산-행렬 내적과 전치 행렬 구하기

- 행렬 내적

In [125]:
A = np.array([[1,2,3,], 
            [4,5,6]])
B = np.array([[7,8],
             [9, 10],
             [11, 12]])
dot_product = np.dot(A, B)
print(dot_product)

[[ 58  64]
 [139 154]]


- 전치 행렬

In [127]:
A = np.array([[1,2,3,], 
            [4,5,6]])
B = np.array([[7,8],
             [9, 10],
             [11, 12]])
transpose_mat_a = np.transpose(A)
transpose_mat_b = np.transpose(B)
print(transpose_mat_a)
print(transpose_mat_b)

[[1 4]
 [2 5]
 [3 6]]
[[ 7  9 11]
 [ 8 10 12]]
